// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/milhamhidayat/golang-clean-code-v2/domain"
	mock "github.com/stretchr/testify/mock"
)

// DepartmentRepository is an autogenerated mock type for the DepartmentRepository type
type DepartmentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, d
func (_m *DepartmentRepository) Create(ctx context.Context, d *domain.Department) error {
	ret := _m.Called(ctx, d)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Department) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, departmentID
func (_m *DepartmentRepository) Delete(ctx context.Context, departmentID string) error {
	ret := _m.Called(ctx, departmentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, departmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, filter
func (_m *DepartmentRepository) Fetch(ctx context.Context, filter domain.DepartmentFilter) ([]domain.Department, string, error) {
	ret := _m.Called(ctx, filter)

	var r0 []domain.Department
	if rf, ok := ret.Get(0).(func(context.Context, domain.DepartmentFilter) []domain.Department); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Department)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, domain.DepartmentFilter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, domain.DepartmentFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: ctx, departmentID
func (_m *DepartmentRepository) Get(ctx context.Context, departmentID string) (domain.Department, error) {
	ret := _m.Called(ctx, departmentID)

	var r0 domain.Department
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Department); ok {
		r0 = rf(ctx, departmentID)
	} else {
		r0 = ret.Get(0).(domain.Department)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, departmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, d
func (_m *DepartmentRepository) Update(ctx context.Context, d domain.Department) (domain.Department, error) {
	ret := _m.Called(ctx, d)

	var r0 domain.Department
	if rf, ok := ret.Get(0).(func(context.Context, domain.Department) domain.Department); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Get(0).(domain.Department)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Department) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
