version: "3.0"
services:
  web:
    image: employee
    container_name: employee_api
    ports:
      - 8500:8500
    depends_on:
      - mariadb
    env_file:
      - .env
  mariadb:
    image: mariadb:10.4.8
    container_name: employee_mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=employee
      - MYSQL_USER=employee
      - MYSQL_PASSWORD=employee-pass
      - MYSQL_ROOT_PASSWORD=root-pass
