openapi: "3.0.1"
info:
  title: "Employee REST API"
  description: "Employee REST API"
  version: "1.0.0"
servers:
  - url: "localhost:8500"
    description: "Development"
paths:
  "/employees":
    get:
      tags:
        - Employees
      summary: "Fetch employess based on query param"
      operationId: "fetchEmployees"
      security:
        - bearerAuth: []
      parameters:
        - in: "query"
          name: "keyword"
          description: "The keyword for searching employee"
          schema:
            type: "string"
          required: false
        - in: "query"
          name: "num"
          description: "Number of items to be returned in a page. Defaults is 20. To get all employees use __num:all__"
          schema:
            type: "string"
            default: 20
          required: false
        - in: "query"
          name: "ids"
          description: "Comma-separated identifier of the object to be retrived"
          schema:
            type: array
            items:
              type: string
            example: ["1", "3"]
          style: "form"
          explode: false
          required: false
        - in: "query"
          name: "dept_ids"
          description: "Comma-separated identifier department ids"
          schema:
            type: array
            items:
              type: string
            example: ["1", "3"]
          style: "form"
          explode: false
          required: false
      responses:
        "200":
          description: "Return array of employees"
          headers:
            X-Cursor:
              description: "The cursor for getting next page"
              schema:
                type: "string"
            ETag:
              description: "Entity-Tag used for caching"
              schema:
                type: "string"
